### ISSUE TITLE
question

### ISSUE THREAD

**Issue by geraldstanje** [stainless-steel/dwt#2]
Hi,

is there a way to use call the discrete wavelet from python? if yes, how?

Thanks,
Gerald

**Comment by IvanUkhov** [comment]
I have no experience in calling Rust from Python, but a [quick search](https://duckduckgo.com/?q=call+rust+from+python) suggests that it’s very much doable; have a look at [this](https://avacariu.me/articles/2014/calling-rust-from-python) post, for instance. I’m curious what your motivation is. Why don’t you want to use a Python library for DWT such as [PyWavelets](https://github.com/PyWavelets/pywt)?

**Comment by geraldstanje** [comment]
@IvanUkhov I tried to use PyWavelets but my result differs from R: https://github.com/PyWavelets/pywt/issues/186

**Comment by IvanUkhov** [comment]
I see. In such cases, I usually reside to some battle-tested implementation for a reliable reference. In the case of DWT, I guess [GSL](http://www.gnu.org/software/gsl/manual/html_node/Wavelet-Transforms.html) is one such implementation.

**Comment by geraldstanje** [comment]
@IvanUkhov do you think its a bug in PyWavelets or did I use the wrong settings?

**Comment by IvanUkhov** [comment]
Sorry, I have no idea, but if you’re in doubt, check against a third implementation.
